//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IXF_TRANSACTION
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Transaction_DATETIME { get; set; }
        public Nullable<int> TRANSACTION_TYPE_FK { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> AccountNumber { get; set; }
    
        public virtual IXF_ACCOUNT IXF_ACCOUNT { get; set; }
    }
}
